apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: logio-build
  template: logio-build-template
metadata:
  name: logio-build
  namespace: openshift
objects:

#Import image from axternal repo to lockal
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: nodejs_alpine
    namespace: ${IMEGE_PROJECT}
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: roskamach/nodejs_alpine:v6.9.5
      from:
        kind: DockerImage
        name: roskamach/nodejs_alpine:v6.9.5
      generation: 2
      importPolicy: {}
      name: v6.9.5
      referencePolicy:
        type: Source

#ImageStream for builded a
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: logio_alpine
    namespace: ${IMEGE_PROJECT}
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: docker-registry.default.svc/${IMEGE_PROJECT}/logio_alpine

#ImageStream for builded a
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: harvester_alpine
    namespace: ${IMEGE_PROJECT}
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: docker-registry.default.svc/${IMEGE_PROJECT}/harvester_alpine

#Create build with docker strategy for Logio Server
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: logio-alpine
    namespace: ${BUILD_PROJECT}
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: logio_alpine:latest
        namespace: ${IMEGE_PROJECT}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    # serviceAccount: deployer
    source:
      contextDir: /build/logio
      git:
        uri: https://github.com/ros-kamach/log.io_alpine
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs_alpine:v6.9.5
          namespace: ${IMEGE_PROJECT}
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: eRWXyQKLJT9qXSZzWdNB
      type: GitHub
    - generic:
        secret: aNSpMKtoDrqplwXCFnw4
      type: Generic
    - type: ConfigChange
    # - imageChange:
    #     lastTriggeredImageID: roskamach/nodejs_alpine
    #   type: ImageChange


#Create build with docker strategy for Harvester
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: harvester-alpine
    namespace: ${BUILD_PROJECT}
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: harvester_alpine:latest
        namespace: ${IMEGE_PROJECT}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: /build/logio
      git:
        uri: https://github.com/ros-kamach/log.io_alpine
      type: Git
    strategy:
      dockerStrategy:
        env:
          #Apply script that install openshif cli
          - name: INSTALL_OPENSHIFT_CLI
            value: 'yes'
        from:
          kind: ImageStreamTag
          name: nodejs_alpine:v6.9.5
          namespace: ${IMEGE_PROJECT}
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: eRWXyQKLJT9qXSZzWdNB
      type: GitHub
    - generic:
        secret: aNSpMKtoDrqplwXCFnw4
      type: Generic
    - type: ConfigChange
    # - imageChange:
    #     lastTriggeredImageID: roskamach/logio_alpine
    #   type: ImageChange

parameters:
- description: Project (Build)
  displayName: Project (Build)
  name: BUILD_PROJECT
  # value: "jenkins-ci"
- description: Project (Image)
  displayName: Project (Image)
  name: IMEGE_PROJECT
  # value: openshift