apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: logio-build
  template: logio-build-template
metadata:
  name: logio-build
  namespace: openshift
objects:

#Import image from axternal repo to lockal
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: nodejs_alpine
    namespace: ${BUILD_PROJECT}
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: ${NODEJS_IMAGE}
      from:
        kind: DockerImage
        name: ${NODEJS_IMAGE}
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source

#ImageStream for builded a
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: logio_alpine
    namespace: ${BUILD_PROJECT}
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: docker-registry.default.svc/${BUILD_PROJECT}/logio_alpine

#ImageStream for builded a
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: harvester_alpine
    namespace: ${BUILD_PROJECT}
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: docker-registry.default.svc/${BUILD_PROJECT}/harvester_alpine

#Create build with docker strategy for Logio Server
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: logio-alpine
    namespace: ${BUILD_PROJECT}
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: logio_alpine:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: ${LOGIO_CONTEXT_DIR}
      git:
        uri: ${LOGIO_REPO}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs_alpine:latest
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    # - github:
    #     secret: eRWXyQKLJT9qXSZzWdNB
    #   type: GitHub
    # - generic:
    #     secret: aNSpMKtoDrqplwXCFnw4
    #   type: Generic
    - type: ConfigChange
    # - imageChange:
    #     lastTriggeredImageID: roskamach/nodejs_alpine
    #   type: ImageChange


#Create build with docker strategy for Harvester
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: harvester-alpine
    namespace: ${BUILD_PROJECT}
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: harvester_alpine:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: ${HARVESTER_CONTEXT_DIR}
      git:
        uri: ${HARVESTER_REPO}
      type: Git
    strategy:
      dockerStrategy:
        env:
          #Apply script that install openshif cli
          - name: INSTALL_OPENSHIFT_CLI
            value: 'yes'
        from:
          kind: ImageStreamTag
          name: nodejs_alpine:latest
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    # - github:
    #     secret: eRWXyQKLJT9qXSZzWdNB
    #   type: GitHub
    # - generic:
    #     secret: aNSpMKtoDrqplwXCFnw4
    #   type: Generic
    - type: ConfigChange

parameters:
- description: Project (Namespace)
  displayName: Project (Namespace)
  name: BUILD_PROJECT
  value: "openshift"
- description: Nodejs Image (from)
  displayName: Nodejs Image (from)
  name: NODEJS_IMAGE
  value: "roskamach/nodejs_alpine:v6.9.5"
- description: logio server Dockerfile repo (from)
  displayName: logio server Dockerfile repo (from)
  name: LOGIO_REPO
  value: "https://github.com/ros-kamach/log.io_openshift"
- description: logio server Dockerfile context dir (from)
  displayName: logio server Dockerfile context dir (from)
  name: LOGIO_CONTEXT_DIR
  value: "/build/logio"
- description: harvester Dockerfile repo (from)
  displayName: harvester Dockerfile repo (from)
  name: HARVESTER_REPO
  value: "https://github.com/ros-kamach/log.io_openshift"
- description: harvester Dockerfile context dir (from)
  displayName: harvester Dockerfile context dir (from)
  name: HARVESTER_CONTEXT_DIR
  value: "/build/logio"