apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: logio-build
  template: logio-build-template
metadata:
  name: logio-build
  namespace: openshift
objects:

#Create build with docker strategy (Thunder)
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: logio-alpine
    namespace: jenkins-ci
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: logio_alpine:v6.9.5
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: /build/logio
      git:
        uri: https://github.com/ros-kamach/log.io_alpine
      type: Git
    strategy:
      dockerStrategy:
        # env:
        #   - name: PHP_MEMORY_LIMIT
        #     value: 256M
        #   - name: DRUSH_INSTALL
        #     value: 'yes'
        #   - name: PROMETHEUS_METRICS_INSTALL
        #     value: 'yes'
        #   - name: SITE_INSTALL
        #     # value: 'yes'
        #     value: 'no'
        #   - name: ENABLE_METRICS
        #     # value: 'yes'
        #     value: 'no'
        from:
          kind: ImageStreamTag
          name: roskamach/logio_alpine:v6.9.5
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: eRWXyQKLJT9qXSZzWdNB
      type: GitHub
    - generic:
        secret: aNSpMKtoDrqplwXCFnw4
      type: Generic
    - type: ConfigChange
    - imageChange:
        lastTriggeredImageID: roskamach/logio_alpine
      type: ImageChange


#ImageStream for builded a
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: logio_alpine
    namespace: jenkins-ci
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: docker-registry.default.svc/jenkins-ci/logio_alpine
